[HLStatsX]
DaemonHost = "127.0.0.1"
DaemonPort = 27500
ServerIp = "5.135.143.217"
ServerPort = 27015
ProxyKey = ""
MaxPlayers = 32
ReceiverPort = 27015
MenuType = "CustomHud"
CustomMenuLayout = "resources/panorama/layout/custom_game/hlx_menu.xml"
